# Use the official PostgreSQL image as base
FROM timescale/timescaledb:latest-pg13

# Set environment variables for Postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=mysecretpassword
ENV POSTGRES_DB=stock_data

# Expose the PostgreSQL port
EXPOSE 5432
