const FLUSHING_TO_DB_INTERVAL = 2 * 60 * 1000; // every 2 mins
const RUNNING_AGGREGATIONS_INTERVAL = 10 * 60 * 1000; // every 10 mins
const DEFAULT_TOP_STOCKS_LIMIT = 20;
const DEFAULT_SORT_MINUTE = 10;
const MEMORY_MAX_WINDOW = 5 * 60 * 1000; // 5 mins

module.exports = {
  FLUSHING_TO_DB_INTERVAL,
  RUNNING_AGGREGATIONS_INTERVAL,
  DEFAULT_TOP_STOCKS_LIMIT,
  DEFAULT_SORT_MINUTE,
  MEMORY_MAX_WINDOW,
};
